team-ykk/the-cd

- app/views/publics/items/index.html.erb
- config/routes.rb
> [Edit]public側のURLの調整

- app/assets/javascripts/admins/application.coffee
- app/assets/javascripts/publics/application.coffee
- app/assets/stylesheets/admins/application.scss
- app/assets/stylesheets/publics/application.scss
- app/controllers/admins/add_items_controller.rb
- app/controllers/admins/application_controller.rb
- app/controllers/admins/artists_controller.rb
- app/controllers/admins/contact_replies_controller.rb
- app/controllers/admins/contacts_controller.rb
- app/controllers/admins/endusers_controller.rb
- app/controllers/admins/freights_controller.rb
- app/controllers/admins/genres_controller.rb
- app/controllers/admins/items_controller.rb
- app/controllers/admins/labels_controller.rb
- app/controllers/admins/orders_controller.rb
- app/controllers/admins/reviews_controller.rb
- app/controllers/publics/addresses_controller.rb
- app/controllers/publics/application_controller.rb
- app/controllers/publics/carts_controller.rb
- app/controllers/publics/contacts_controller.rb
- app/controllers/publics/endusers_controller.rb
- app/controllers/publics/favorites_controller.rb
- app/controllers/publics/items_controller.rb
- app/controllers/publics/orders_controller.rb
- app/controllers/publics/reviwes_controller.rb
- app/helpers/admins/application_helper.rb
- app/helpers/publics/application_helper.rb
- test/controllers/admins/application_controller_test.rb
- test/controllers/publics/application_controller_test.rb
admin側とpublic側にApplicationコントローラーを作成しました。確認ください
> [Edit]admin側とpublic側にApplicationコントローラーを作成

- app/controllers/publics/items_controller.rb
- app/views/publics/items/index.html.erb
- app/views/publics/items/show.html.erb
- config/initializers/kaminari_config.rb
- config/routes.rb
devise_forの位置を修正し、中身のコントローラーの指定を変更しました。
> [Edit]devise_forの位置を修正

- app/assets/javascripts/application.js
- app/assets/stylesheets/publics/registrations.scss
- app/controllers/publics/registrations_controller.rb
- app/models/enduser.rb
- app/views/publics/confirmations/new.html.erb
- app/views/publics/mailer/confirmation_instructions.html.erb
- app/views/publics/mailer/email_changed.html.erb
- app/views/publics/mailer/password_change.html.erb
- app/views/publics/mailer/reset_password_instructions.html.erb
- app/views/publics/mailer/unlock_instructions.html.erb
- app/views/publics/passwords/edit.html.erb
- app/views/publics/passwords/new.html.erb
- app/views/publics/registrations/edit.html.erb
- app/views/publics/registrations/new.html.erb
- app/views/publics/sessions/new.html.erb
- app/views/publics/shared/_error_messages.html.erb
- app/views/publics/shared/_links.html.erb
- app/views/publics/unlocks/new.html.erb
- app/views/users/registrations/new.html.erb
- config/initializers/assets.rb
> [Add]会員登録の画面の作成

- app/views/layouts/application.html.erb
> [edit]header_enduser_logined

- app/views/layouts/application.html.erb
> [edit]re_header_enduser_logined

- app/assets/stylesheets/publics/items.scss
- app/controllers/publics/items_controller.rb
- app/models/item.rb
- app/views/publics/items/index.html.erb
- app/views/publics/items/show.html.erb
- config/initializers/kaminari_config.rb
- db/migrate/20191118113227_add_cart_id_to_cart_item.rb
- db/migrate/20191118113441_remove_enduser_id_from_cart_item.rb
- db/schema.rb
- db/seeds.rb
商品一覧・商品詳細（エンドユーザー側）画面を作成しました。
中間テーブルのカラムを編集しました。（cart_idを追加　enduser_idを削除）
> [Edit]商品一覧・詳細画面[Edit]中間テーブルのカラムの編集

- app/assets/stylesheets/admins/additems.scss
- app/assets/stylesheets/admins/items.scss
- app/assets/stylesheets/application.scss
- app/controllers/admins/additems_controller.rb
- app/controllers/admins/freights_controller.rb
- app/controllers/admins/items_controller.rb
- app/models/item.rb
- app/views/admins/additems/new.html.erb
- app/views/admins/freights/edit.html.erb
- app/views/admins/freights/index.html.erb
- app/views/admins/items/_disc_fields.html.erb
- app/views/admins/items/_item_form.html.erb
- app/views/admins/items/_song_fields.html.erb
- app/views/admins/items/edit.html.erb
- app/views/admins/items/index.html.erb
- app/views/admins/items/new.html.erb
- app/views/admins/items/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
> [add]管理者側:商品追加機能/入荷機能/商品詳細機能/商品一覧機能/

- app/controllers/publics/registrations_controller.rb
> [Add]会員登録と同時にカート作成する機能の追加

- app/controllers/admins/contact_replies_controller.rb
- app/views/admins/contact_replies/show.html.erb
- app/views/admins/contacts/index.html.erb
- app/views/admins/endusers/edit.html.erb
- app/views/admins/endusers/index.html.erb
- app/views/admins/endusers/show.html.erb
- app/views/publics/contacts/new.html.erb
- app/views/publics/endusers/edit.html.erb
- app/views/publics/endusers/show.html.erb
- config/environments/development.rb
- config/routes.rb
- db/migrate/20191121034559_remove_total_price_from_cart.rb
- db/migrate/20191121034948_remove_quantity_from_cart_items.rb
- db/migrate/20191121035059_add_quantity_to_cart_items.rb
- db/migrate/20191121035501_add_contact_reply_id_to_contacs.rb
- db/schema.rb
各種カラムの追加といいね、レビューをitemにネストしました。
> 各種カラム追加、いいね、レビューをネスト

- app/assets/stylesheets/publics/carts.scss
- app/assets/stylesheets/publics/items.scss
- app/controllers/publics/cart_items_controller.rb
- app/controllers/publics/carts_controller.rb
- app/controllers/publics/items_controller.rb
- app/controllers/publics/reviews_controller.rb
- app/views/layouts/application.html.erb
- app/views/publics/carts/show.html.erb
- app/views/publics/items/show.html.erb
> [Edit]ヘッダーのカート一覧リンクの修正

- app/controllers/publics/cart_items_controller.rb
- app/controllers/publics/carts_controller.rb
- app/views/publics/carts/show.html.erb
- config/routes.rb
rute.rbのcart_item に　destroy を追加しました
> [Add]中間テーブルに削除機能のルートを追加しました

- app/assets/stylesheets/application.scss
- app/controllers/admins/additems_controller.rb
- app/controllers/admins/application_controller.rb
- app/controllers/admins/artists_controller.rb
- app/controllers/admins/genres_controller.rb
- app/controllers/admins/items_controller.rb
- app/controllers/admins/labels_controller.rb
- app/models/item.rb
- app/views/admins/additems/new.html.erb
- app/views/admins/artists/new.html.erb
- app/views/admins/freights/edit.html.erb
- app/views/admins/genres/new.html.erb
- app/views/admins/items/edit.html.erb
- app/views/admins/items/new.html.erb
- app/views/admins/labels/new.html.erb
> [edit]リダイレクト編集/調整

- app/assets/stylesheets/publics/carts.scss
- app/assets/stylesheets/publics/items.scss
- app/controllers/publics/cart_items_controller.rb
- app/controllers/publics/carts_controller.rb
- app/controllers/publics/items_controller.rb
- app/models/item.rb
- app/views/publics/carts/show.html.erb
- app/views/publics/items/show.html.erb
> [Add]カートの数量変更・削除機能

- app/assets/stylesheets/publics/carts.scss
- app/assets/stylesheets/publics/items.scss
- app/controllers/publics/carts_controller.rb
- app/controllers/publics/favorites_controller.rb
- app/controllers/publics/items_controller.rb
- app/controllers/publics/reviews_controller.rb
- app/models/item.rb
- app/views/publics/carts/show.html.erb
- app/views/publics/items/show.html.erb
レビュー機能　いいね機能　カート機能（数の追加・削除・ダブり解消）
> [Add]レビュー機能　いいね機能　カート機能（数の追加・削除・ダブり解消）

- app/controllers/admins/endusers_controller.rb
- app/controllers/publics/endusers_controller.rb
- app/views/admins/endusers/index.html.erb
- app/views/admins/endusers/show.html.erb
- app/views/publics/endusers/show.html.erb
管理者によるユーザーの編集、削除を行えるようにしました。
ユーザーのマイページで'いいね’した商品の一覧が閲覧できるようにしました。
> 管理者によるユーザーの編集　削除。いいねしたもの一覧

- app/controllers/publics/items_controller.rb
- app/models/item.rb
- app/views/publics/items/index.html.erb
- app/views/publics/items/ranking.html.erb
- app/views/publics/items/show.html.erb
- config/initializers/kaminari_config.rb
ログアウト時に商品詳細画面のレイアウトが崩れることを修正しました。
> [Add]商品詳細画面のCSS

- app/assets/stylesheets/publics/carts.scss
- app/assets/stylesheets/publics/items.scss
- app/controllers/application_controller.rb
- app/controllers/publics/application_controller.rb
- app/controllers/publics/carts_controller.rb
- app/controllers/publics/items_controller.rb
- app/controllers/publics/reviews_controller.rb
- app/models/review.rb
- app/views/publics/carts/show.html.erb
- app/views/publics/items/index.html.erb
- app/views/publics/items/ranking.html.erb
- app/views/publics/items/show.html.erb
ランキングページの完成、URL直うちの対策、レビュー投稿機能を作成しました。
> [Add]ランキングページ・URL直うちの対策・レビュー機能

- Gemfile
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/admins/application_controller.rb
- app/controllers/admins/artists_controller.rb
- app/controllers/admins/freights_controller.rb
- app/controllers/admins/genres_controller.rb
- app/controllers/admins/items_controller.rb
- app/controllers/admins/labels_controller.rb
- app/controllers/application_controller.rb
- app/models/additem.rb
- app/models/artist.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/label.rb
- app/views/admins/additems/index.html.erb
- app/views/admins/additems/new.html.erb
- app/views/admins/artists/new.html.erb
- app/views/admins/freights/edit.html.erb
- app/views/admins/freights/index.html.erb
- app/views/admins/genres/new.html.erb
- app/views/admins/items/_disc_fields.html.erb
- app/views/admins/items/_song_fields.html.erb
- app/views/admins/items/edit.html.erb
- app/views/admins/items/index.html.erb
- app/views/admins/items/new.html.erb
- app/views/admins/items/show.html.erb
- app/views/admins/labels/new.html.erb
- config/routes.rb
> [Fix]送料変更、アーティスト・ジャンル・レーベル追加

- app/controllers/publics/registrations_controller.rb
> [Fix]registration.controller修正

- app/controllers/admins/items_controller.rb
- app/controllers/admins/reviews_controller.rb
- app/controllers/application_controller.rb
- app/models/item.rb
- app/views/admins/additems/index.html.erb
- app/views/admins/items/index.html.erb
- app/views/admins/items/show.html.erb
- config/initializers/kaminari_config.rb
商品一覧機能、レビュー機能、商品追加機能の修正
その他微調整済み
> [Fix]商品一覧機能、レビュー機能、商品追加機能の修正

- app/controllers/publics/carts_controller.rb
- app/controllers/publics/reviews_controller.rb
- app/views/publics/carts/show.html.erb
- app/views/publics/items/index.html.erb
- app/views/publics/items/ranking.html.erb
- app/views/publics/items/show.html.erb
商品詳細コードのインデント、商品一覧・ランキング画面のCSSを整えました。
> [Add]商品詳細画面のインデントを整えました

- app/controllers/publics/orders_controller.rb
- app/views/publics/orders/new.html.erb
購入すると在庫減少、在庫が０になると販売停止になるようにしました。
> [Add]購入すると在庫減少、０になると販売停止

- app/assets/stylesheets/admins/contacts.scss
- app/assets/stylesheets/admins/endusers.scss
- app/assets/stylesheets/admins/orders.scss
- app/assets/stylesheets/publics/contacts.scss
- app/assets/stylesheets/publics/endusers.scss
- app/assets/stylesheets/publics/orders.scss
- app/controllers/admins/endusers_controller.rb
- app/controllers/publics/endusers_controller.rb
- app/controllers/publics/orders_controller.rb
- app/views/admins/contacts/index.html.erb
- app/views/admins/contacts/show.html.erb
- app/views/admins/endusers/show.html.erb
- app/views/admins/orders/edit.html.erb
- app/views/admins/orders/index.html.erb
- app/views/publics/contacts/complete.html.erb
- app/views/publics/contacts/new.html.erb
- app/views/publics/endusers/show.html.erb
- app/views/publics/orders/index.html.erb
> 購入者履歴完成、レイアウト調整完了

- app/controllers/publics/items_controller.rb
- app/controllers/publics/orders_controller.rb
> [Edit]購入と同時に在庫を減らして注文確定

- app/views/admins/items/index.html.erb
- app/views/admins/items/ranking.html.erb
管理者の商品一覧ページとランキングページのレイアウトを修正しました
> [Edit]管理者の商品一覧ページとランキングページをレイアウトの修正

- app/controllers/publics/orders_controller.rb
- app/models/enduser.rb
- app/views/publics/orders/new.html.erb
**商品の価格を変えるとカートの商品も値段変更　購入画面のバリデートを追加**
> [Edit]商品の価格を変えるとカートの商品も値段変更　購入画面のバリデートを追加

- app/assets/stylesheets/publics/orders.scss
- app/controllers/admins/items_controller.rb
> [Add]購入時のエラーメッセージのCSS追加

- app/assets/stylesheets/admins/contacts.scss
- app/assets/stylesheets/admins/endusers.scss
- app/assets/stylesheets/admins/orders.scss
- app/assets/stylesheets/publics/orders.scss
- app/controllers/admins/endusers_controller.rb
- app/controllers/publics/contacts_controller.rb
- app/controllers/publics/endusers_controller.rb
- app/views/admins/contacts/index.html.erb
- app/views/admins/contacts/show.html.erb
- app/views/admins/endusers/index.html.erb
- app/views/admins/orders/edit.html.erb
- app/views/admins/orders/index.html.erb
- app/views/publics/contacts/new.html.erb
- app/views/publics/orders/index.html.erb
- config/routes.rb
> 各ページレイアウト 調整

- app/assets/stylesheets/admins/contacts.scss
- app/controllers/admins/contact_replies_controller.rb
- app/views/admins/contacts/index.html.erb
- app/views/admins/contacts/show.html.erb
- db/migrate/20191128071250_rename_satatus_column_to_contacts.rb
- db/schema.rb
> 問い合わせのステータ変完了

- app/views/publics/addresses/new.html.erb
> [Edit]住所追加画面のレイアウト編集

- config/environments/development.rb
> [Revert]メールアドレスの削除
